# Generated by Django 4.2.4 on 2023-08-04 05:59

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('odjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
